name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Test (Go ${{ matrix.go }} / ${{ matrix.os }})
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        go: ["1.14.x", "oldstable", "stable"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy
      - name: Vet
        run: go vet ./...
      - name: Static analysis
        run: go run honnef.co/go/tools/cmd/staticcheck@latest ./...
      - name: Check vulnerabilities
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
      - name: Test
        run: go test -race -vet=off ./...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
